version: '2'

services:
  znc:
    image: 'vircung/znc'
    ports:
      - '$IRC_PORT:6667'
    volumes:
      - '$VOLUMES_HOME/znc:/znc-data'
    restart: always

  ghost:
    image: 'ghost:alpine'
    ports:
      - '80:2368'
    volumes:
      - '$VOLUMES_HOME/ghost:/var/lib/ghost'
    restart: always
