version: '3.1'

services:
  znc:
    image: 'vircung/znc'
    ports:
      - '$IRC_PORT:6667'
    volumes:
      - '$VOLUMES_HOME/znc:/znc-data'
    restart: unless-stopped

  ghost:
    image: 'ghost:alpine'
    ports:
      - '80:2368'
    volumes:
      - '$VOLUMES_HOME/ghost:/var/lib/ghost'
    restart: unless-stopped

  postgres:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    volumes:
      - '$VOLUMES_HOME/postgres:/var/lib/postgresql'
    restart: unless-stopped
